### PR TITLE
feat: add new options to generate command

### PR DESCRIPTION
**Pull request by yubathom**
related to #8

### CODE REVIEW

**Review by jamesgeorge007 — COMMENTED** [review]
It is better to use [enquirer](https://github.com/enquirer/enquirer), which is a lightweight alternative with a similar API.

**Comment by jamesgeorge007** [comment]
Renamed `--install` flag to `--skip-install` and added a couple of test cases.

**Comment by yubathom** [comment]
New option added, request buttons `-r, --request-buttons` (only for GET requests). [Check this gif](https://user-images.githubusercontent.com/4117768/93141771-2814f200-f6bb-11ea-941b-8b023722888f.gif) and last request of the [npm run docs:build](http://unkempt-jail.surge.sh) deployed.

I'm not sure about the location of the location of the vue components (now at `src/utils/components/`). Maybe add the components as package so we could do the tests of the components separated from the cli.

**Review by jamesgeorge007 — APPROVED** [review]
Feel free to revisit what's leftover in a follow-up PR.

**Comment by yubathom** [comment]
> 
> 
> Feel free to revisit what's leftover in a follow-up PR.

please check #12

**Pull request merged**
